---
- name: Apache server installed
  hosts: web
  gather_facts: false
  become: yes
  tasks:

  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: copy index.html
    copy:
      src: index.html
      dest: /var/www/html/

  - name: open up https
    firewalld:
      zone: public
      service: https
      permanent: true
      immediate: true
      state: enabled
